# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "22a72f7b981d8675311736a675aed795"
name = "Bundler"
handle = "bundler-46"
application_url = "https://xl-elegant-tcp-top.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bundling-app-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://xl-elegant-tcp-top.trycloudflare.com/auth/callback",
  "https://xl-elegant-tcp-top.trycloudflare.com/auth/shopify/callback",
  "https://xl-elegant-tcp-top.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
