api_version = "2024-07"

[[extensions]]
name = "t:name"
handle = "bundle-details"
type = "ui_extension"


# Both extension points are required
[[extensions.targeting]]
module = "./src/ProductDetailsConfigurationExtension.jsx"
# The target used here must match the target used in the module file (./src/ProductDetailsConfigurationExtension.jsx)
target = "admin.product-details.configuration.render"


[[extensions.targeting]]
module = "./src/ProductVariantDetailsConfigurationExtension.jsx"
# The target used here must match the target used in the module file (./src/ProductVariantDetailsConfigurationExtension.jsx)
target = "admin.product-variant-details.configuration.render"
